/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;


/**
 *
 * @author jpbri
 */
public class VistaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form VistaUsuario
     */
    public VistaAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_menu_proveedor = new javax.swing.JButton();
        btn_listar_usuario = new javax.swing.JButton();
        btn_Servicios = new javax.swing.JButton();
        btn_reportes = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(189, 189, 189));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_menu_proveedor.setBackground(new java.awt.Color(49, 69, 84));
        btn_menu_proveedor.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu_proveedor.setText("Mantenedor Proveedores");
        btn_menu_proveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_menu_proveedor.setMaximumSize(new java.awt.Dimension(89, 22));
        btn_menu_proveedor.setMinimumSize(new java.awt.Dimension(89, 22));
        btn_menu_proveedor.setPreferredSize(new java.awt.Dimension(89, 22));
        btn_menu_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_proveedors(evt);
            }
        });

        btn_listar_usuario.setBackground(new java.awt.Color(49, 69, 84));
        btn_listar_usuario.setForeground(new java.awt.Color(255, 255, 255));
        btn_listar_usuario.setText("Mantenedor Usuarios");
        btn_listar_usuario.setMaximumSize(new java.awt.Dimension(89, 22));
        btn_listar_usuario.setMinimumSize(new java.awt.Dimension(89, 22));
        btn_listar_usuario.setPreferredSize(new java.awt.Dimension(89, 22));
        btn_listar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listar_usuarios(evt);
            }
        });

        btn_Servicios.setBackground(new java.awt.Color(49, 69, 84));
        btn_Servicios.setForeground(new java.awt.Color(255, 255, 255));
        btn_Servicios.setText("Mantenedor de servicios");
        btn_Servicios.setActionCommand("Mantenedor Servicios");
        btn_Servicios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Servicios.setMaximumSize(new java.awt.Dimension(89, 22));
        btn_Servicios.setMinimumSize(new java.awt.Dimension(89, 22));
        btn_Servicios.setPreferredSize(new java.awt.Dimension(89, 22));
        btn_Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Servicioss(evt);
            }
        });

        btn_reportes.setBackground(new java.awt.Color(49, 69, 84));
        btn_reportes.setForeground(new java.awt.Color(255, 255, 255));
        btn_reportes.setText("Generación reportes");
        btn_reportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_reportes.setMaximumSize(new java.awt.Dimension(89, 22));
        btn_reportes.setMinimumSize(new java.awt.Dimension(89, 22));
        btn_reportes.setPreferredSize(new java.awt.Dimension(89, 22));
        btn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportess(evt);
            }
        });

        btn_salir.setBackground(new java.awt.Color(251, 200, 51));
        btn_salir.setForeground(new java.awt.Color(43, 61, 123));
        btn_salir.setText("Sign Out");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(29, 41, 83));

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ServiExpress");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2))
                    .addComponent(jLabel5))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_listar_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_menu_proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Servicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_salir)
                .addGap(31, 31, 31)
                .addComponent(btn_listar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_menu_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_Servicios, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_listar_usuarios(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listar_usuarios

        VistaListarUsuario listar = new VistaListarUsuario();
        listar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_listar_usuarios

    private void btn_menu_proveedors(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_proveedors
        VistaMenuProveedor menu_proveedores = new VistaMenuProveedor();
        menu_proveedores.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_menu_proveedors

    private void btn_reportess(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportess
        VistaGeneracionInformes menu_informes = new VistaGeneracionInformes();
        menu_informes.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_reportess

    private void btn_Servicioss(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Servicioss
        VistaMantenedorServicios menu_servicios = new VistaMantenedorServicios();
        menu_servicios.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_Servicioss

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        VistaPrincipal vp = new VistaPrincipal();
        vp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Servicios;
    private javax.swing.JButton btn_listar_usuario;
    private javax.swing.JButton btn_menu_proveedor;
    private javax.swing.JButton btn_reportes;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
