package presentacion;


import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Logica_Proveedor;
import logica.Producto;

import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import static java.lang.Integer.parseInt;
import logica.Logica_Orden;
import logica.Orden;



public class VistaGenerarOrden extends javax.swing.JFrame {
    /**
     * Creates new form VistaListarUsuario
     */
    
    
    public VistaGenerarOrden() {
        Orden orden = new Orden();
        initComponents();
        this.setLocationRelativeTo(null);
        txt_total.setText("0");
        txt_proveedor.setEditable(false);
        VistaMenuProveedor vistaMenuProv = new VistaMenuProveedor();
        txt_proveedor.setText(vistaMenuProv.prov);
      
        
        
        ArrayList<Producto> listaProductos = new ArrayList<>();
        Logica_Proveedor lg_prov = new Logica_Proveedor();
        
        try{
            String nombre = txt_buscar.getText();
            listaProductos = lg_prov.listarProductos(vistaMenuProv.prov);
            
            DefaultTableModel tablaModelo = (DefaultTableModel)tbl_productos_stock.getModel();
            tablaModelo.setRowCount(0);
            
            for(Producto x: listaProductos){
               Object[] fila = {
                x.getId(),
                x.getNombre_producto(),
                x.getPrecio()};
               
                tablaModelo.addRow(fila);
                System.out.println("id:" + x.getId());
            }
     
        }
        catch(Exception err){
            
            System.out.println("Error: " + err.getMessage());
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_productos_stock = new javax.swing.JTable();
        txt_buscar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_generar_orden = new javax.swing.JButton();
        btn_anadir_lista = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_carrito = new javax.swing.JTable();
        label2 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        txt_proveedor = new javax.swing.JTextField();
        total = new java.awt.Label();
        txt_total = new javax.swing.JTextField();
        txt_prueba = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        btn_atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(189, 189, 189));
        setUndecorated(true);

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setPreferredSize(new java.awt.Dimension(100, 20));
        label1.setText("Generar orden de compra");

        tbl_productos_stock.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl_productos_stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre Producto", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_productos_stock);

        btn_buscar.setBackground(new java.awt.Color(49, 69, 84));
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_generar_orden.setBackground(new java.awt.Color(111, 212, 88));
        btn_generar_orden.setText("Generar orden");
        btn_generar_orden.setActionCommand("");
        btn_generar_orden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generar_ordenActionPerformed(evt);
            }
        });

        btn_anadir_lista.setBackground(new java.awt.Color(54, 49, 68));
        btn_anadir_lista.setForeground(new java.awt.Color(255, 255, 255));
        btn_anadir_lista.setText("Añadir a la lista");
        btn_anadir_lista.setActionCommand("");
        btn_anadir_lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anadir_listaActionPerformed(evt);
            }
        });

        tbl_carrito.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl_carrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre Producto", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_carrito);

        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setPreferredSize(new java.awt.Dimension(100, 20));
        label2.setText("En carrito");

        jLabel1.setText("Nombre proveedor:");

        txt_proveedor.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_proveedorCaretUpdate(evt);
            }
        });
        txt_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_proveedorActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        total.setPreferredSize(new java.awt.Dimension(100, 20));
        total.setText("Total: $ ");

        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });

        txt_prueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pruebaActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(29, 41, 83));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N

        btn_atras.setBackground(new java.awt.Color(251, 200, 51));
        btn_atras.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        btn_atras.setForeground(new java.awt.Color(255, 255, 255));
        btn_atras.setText("Atras");
        btn_atras.setActionCommand("");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btn_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn_anadir_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_prueba, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_generar_orden, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txt_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_buscar))
                            .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txt_prueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_generar_orden, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_anadir_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        ArrayList<Producto> listaProductos = new ArrayList<>();
        Logica_Proveedor lg_prov = new Logica_Proveedor();
        
        try{
            String nombre = txt_buscar.getText();
            listaProductos = lg_prov.listarProductos(nombre);
            
            DefaultTableModel tablaModelo = (DefaultTableModel)tbl_productos_stock.getModel();
            tablaModelo.setRowCount(0);
            
            for(Producto x: listaProductos){
               Object[] fila = {
                x.getId(),
                x.getNombre_producto(),
                x.getPrecio()};
               
                tablaModelo.addRow(fila);
                System.out.println("id:" + x.getId());
            }
     
        }
        catch(Exception err){
            
            System.out.println("Error: " + err.getMessage());
        }  
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_generar_ordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generar_ordenActionPerformed
        try{
            int numeroAleatorio = (int) (Math.random()*25+1);
            Document documento = new Document();
            DefaultTableModel tablaModelo = (DefaultTableModel)tbl_carrito.getModel();
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/Orden de compra"+ numeroAleatorio+".pdf")).setInitialLeading(30);
            
            documento.open();
            
            Image img = Image.getInstance("src/img/logo_adm.png");
            
            Paragraph fecha = new Paragraph();
            fecha.add(Chunk.NEWLINE);
            Date date = new Date();
            fecha.add("Fecha: " + new SimpleDateFormat("dd-MM-yyyy").format(date)+ "\n\n");
            
            PdfPTable Encabezado = new PdfPTable(4);
            Encabezado.setWidthPercentage(100);
            Encabezado.getDefaultCell().setBorder(0);
            float[] ColumaEncabezado = new float[]{20f, 30f, 70f, 40f};
            Encabezado.setWidths(ColumaEncabezado);
            Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
            
            Encabezado.addCell(img);
            Encabezado.addCell("");
            Encabezado.addCell("");
            Encabezado.addCell(fecha);
            
            documento.add(Encabezado);
            
            Paragraph Title = new Paragraph();
            Title.setAlignment(Element.ALIGN_CENTER) ; 
            Font negrita = new Font(Font.FontFamily.TIMES_ROMAN, 25, Font.BOLD);
            Title.setFont(negrita);


            Title.add(Chunk.NEWLINE);
            Title.add("Orden de Compra"+"\n\n");
            documento.add(Title);
            
            
            Paragraph Cuerpo = new Paragraph();
            Cuerpo.setAlignment(Element.ALIGN_LEFT); 
            Font negrocuerpo = new Font(Font.FontFamily.TIMES_ROMAN, 14, Font.BOLD);
            Cuerpo.setFont(negrocuerpo);
            
            Cuerpo.add(Chunk.NEWLINE);
            Cuerpo.add("Nombre de la empresa:  " + txt_proveedor.getText()+ "\n\n");
            Cuerpo.add("Ciudad:  Santiago" + "\n\n");
            Cuerpo.add("Total: $ "+ txt_total.getText()+ "\n\n");
            Cuerpo.add(Chunk.NEWLINE);
            documento.add(Cuerpo);
                
            
            PdfPTable tabla = new PdfPTable(3);
            
            tabla.addCell("Codigo");
            tabla.addCell("Nombre de producto");
            tabla.addCell("Precio");
            
            try{
                
                for (int indice = 0; indice < tablaModelo.getRowCount(); indice++){
                String codigo = tbl_carrito.getValueAt(indice, 0).toString();
                String nombre = tbl_carrito.getValueAt(indice, 1).toString();
                String precio = tbl_carrito.getValueAt(indice, 2).toString();

                tabla.addCell(codigo);
                tabla.addCell(nombre);
                tabla.addCell(precio);
                
                
                String dato = codigo + nombre + precio;
                }
                
                
                
                documento.add(tabla);
                
                try{
                    Logica_Orden log_orden = new Logica_Orden();
                    Orden orden = new Orden();
                    
                    orden.setDescripcion(txt_prueba.getText());
                    orden.setEmpleado(txt_prueba.getText());
                    orden.setProveedorn(txt_proveedor.getText());
                    orden.setTotal(parseInt(txt_total.getText()));
                    log_orden.almacenarOrden(orden);
                    JOptionPane.showMessageDialog(rootPane, "Producto Guardado Correctamente!!");
                    
                }catch(Exception err){
                    JOptionPane.showMessageDialog(rootPane, "Error: " + err.getMessage());
                
                }
                
                
        
                

                
                JOptionPane.showMessageDialog(rootPane, "PDF generado correctamente!!");
                
             
                
            }catch(Exception err){
                System.out.println("Error: " + err.getMessage());
            }
            documento.close();
        }catch(Exception err){ 
            System.out.println("Error: " + err.getMessage());
        }
    }//GEN-LAST:event_btn_generar_ordenActionPerformed

    
    
    private void btn_anadir_listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anadir_listaActionPerformed
        int indice = tbl_productos_stock.getSelectedRow();
        String codigo = tbl_productos_stock.getValueAt(indice, 0).toString();
        String nombre = tbl_productos_stock.getValueAt(indice, 1).toString();
        int precio = (int) tbl_productos_stock.getValueAt(indice, 2);
        
        DefaultTableModel tablaModelo = (DefaultTableModel)tbl_carrito.getModel();
        
        
        Object[] fila ={codigo,nombre,precio};
        tablaModelo.addRow(fila);
        
        
        Logica_Proveedor lg = new Logica_Proveedor();
        
        txt_total.setText(lg.sumatoria(precio, Integer.parseInt (txt_total.getText())));
        System.out.println("Error: " + lg.sumatoria(precio, Integer.parseInt (txt_total.getText())));
    }//GEN-LAST:event_btn_anadir_listaActionPerformed

    private void txt_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_proveedorActionPerformed
  
    }//GEN-LAST:event_txt_proveedorActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void txt_proveedorCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_proveedorCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_proveedorCaretUpdate

    private void txt_pruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pruebaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pruebaActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        VistaAdministrador entrar_admin = new VistaAdministrador();
        entrar_admin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_atrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGenerarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGenerarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGenerarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGenerarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaGenerarOrden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anadir_lista;
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_generar_orden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator9;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTable tbl_carrito;
    private javax.swing.JTable tbl_productos_stock;
    private java.awt.Label total;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_proveedor;
    private javax.swing.JTextField txt_prueba;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
