/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorMascota;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Mascota;

/**
 *
 * @author jeanpierrebritocastro
 */
public class BuscarMascota extends javax.swing.JFrame {

    /**
     * Creates new form BuscarMascota
     */
    public BuscarMascota() {
        initComponents();
        cmb_mascota_tipo.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rb_buscar_nombre = new javax.swing.JRadioButton();
        rb_buscar_tipo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mascota = new javax.swing.JTable();
        cmb_mascota_tipo = new javax.swing.JComboBox<>();
        btn_modificar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_almacenar_mascota = new javax.swing.JMenuItem();
        mi_buscar_mascota = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 500));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        jLabel1.setText("BUSCAR MASCOTA");

        grupo.add(rb_buscar_nombre);
        rb_buscar_nombre.setText("BUSCAR POR NOMBRE");
        rb_buscar_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_buscar_nombreActionPerformed(evt);
            }
        });

        grupo.add(rb_buscar_tipo);
        rb_buscar_tipo.setText("BUSCAR POR TIPO");
        rb_buscar_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_buscar_tipoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("NOMBRE");

        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        tbl_mascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null,  new Boolean(false)},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Edad", "Tipo", "Dueño"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_mascota);

        cmb_mascota_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(SELECCIONE)", "PERRO", "GATO", "TORTUGA", "PATO", "MAPACHE" }));
        cmb_mascota_tipo.setFocusTraversalKeysEnabled(false);
        cmb_mascota_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_mascota_tipoActionPerformed(evt);
            }
        });

        btn_modificar.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_Eliminar.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        jMenu1.setText("Opciones");

        mi_almacenar_mascota.setText("Almacenar mascota");
        mi_almacenar_mascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_almacenar_mascotaActionPerformed(evt);
            }
        });
        jMenu1.add(mi_almacenar_mascota);

        mi_buscar_mascota.setText("Buscar Mascota");
        jMenu1.add(mi_buscar_mascota);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quienes somos");

        jMenuItem2.setText("jMenuItem2");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(rb_buscar_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rb_buscar_tipo)
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(btn_buscar)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_mascota_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btn_Eliminar)
                        .addGap(237, 237, 237)
                        .addComponent(btn_modificar)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_buscar_nombre)
                    .addComponent(rb_buscar_tipo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_buscar)
                        .addComponent(cmb_mascota_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modificar)
                    .addComponent(btn_Eliminar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        ArrayList<Mascota> listaMascotas = new ArrayList<>();
        ControladorMascota ctrm = new ControladorMascota();
        try{
           
            String nombre = txt_buscar.getText();
            String tipo = cmb_mascota_tipo.getSelectedItem().toString();

            if(rb_buscar_nombre.isSelected()==true){
            listaMascotas = ctrm.listarMascota(nombre);
            }else if(rb_buscar_tipo.isSelected()==true){
                listaMascotas = ctrm.listarMascotaTipo(tipo);
            }

            DefaultTableModel tablaModelo = (DefaultTableModel)tbl_mascota.getModel();
            tablaModelo.setRowCount(0);
            
            for(Mascota x: listaMascotas){
               Object[] fila = {
                x.getId(),
                x.getNombre(),
                x.getEdad(),
                x.getTipo(),
                x.isPosee_dueno()};
                
                tablaModelo.addRow(fila);
            }            
    }
            catch(Exception err){
            System.out.println("Error: " + err.getMessage());
        }             
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void cmb_mascota_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_mascota_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_mascota_tipoActionPerformed

    private void rb_buscar_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_buscar_tipoActionPerformed
        if(rb_buscar_tipo.isSelected()==true){
            cmb_mascota_tipo.setVisible(true);
        }else{
            cmb_mascota_tipo.setVisible(false);
        }
    }//GEN-LAST:event_rb_buscar_tipoActionPerformed

    private void rb_buscar_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_buscar_nombreActionPerformed
        if(rb_buscar_tipo.isSelected()==false){
            cmb_mascota_tipo.setVisible(false);
        }else{
            cmb_mascota_tipo.setVisible(true);
        }
    }//GEN-LAST:event_rb_buscar_nombreActionPerformed

    private void mi_almacenar_mascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_almacenar_mascotaActionPerformed
       VistaAlmacenarMascota VistaA = new VistaAlmacenarMascota();
       VistaA.setVisible(true);
    }//GEN-LAST:event_mi_almacenar_mascotaActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
       ControladorMascota ctrlm = new ControladorMascota();
        try{
            if(tbl_mascota.getSelectedRow()==-1){
                JOptionPane.showMessageDialog(rootPane, "Seleccione una opción");
            }else{
                
                
            int indice = tbl_mascota.getSelectedRow();
            String codigo = tbl_mascota.getValueAt(indice, 0).toString();
            
            
            ctrlm.eliminaMascota(codigo);
            
            JOptionPane.showMessageDialog(rootPane, "MASCOTA SE ELIMINÓ CORRECTAMENTE");
            btn_buscarActionPerformed(evt);
            }
        }
        catch(Exception err){
            JOptionPane.showMessageDialog(rootPane, "ERROR " + err.getMessage());
        }
    }//GEN-LAST:event_btn_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarMascota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JComboBox<String> cmb_mascota_tipo;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mi_almacenar_mascota;
    private javax.swing.JMenuItem mi_buscar_mascota;
    private javax.swing.JRadioButton rb_buscar_nombre;
    private javax.swing.JRadioButton rb_buscar_tipo;
    private javax.swing.JTable tbl_mascota;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
