/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorMascota;
import javax.swing.JOptionPane;
import modelo.Mascota;

/**
 *
 * @author jeanpierrebritocastro
 */
public class VistaAlmacenarMascota extends javax.swing.JFrame {

    /**
     * Creates new form VistaAlmacenarMascota
     */
    public VistaAlmacenarMascota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_edad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmb_tipo = new javax.swing.JComboBox<>();
        chk_atenciones = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_dueño = new javax.swing.JTextField();
        chk_dueño = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        btn_almacenar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_descripcion = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_almacenarMascota = new javax.swing.JMenuItem();
        mi_buscarMascota = new javax.swing.JMenuItem();
        mi_listarMascota = new javax.swing.JMenuItem();
        mi_eliminarModificar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MediPet");
        setSize(new java.awt.Dimension(800, 500));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("NUEVA MASCOTA");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel2.setText("NOMBRE:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel3.setText("EDAD:");

        txt_edad.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_edad.setText("0");
        txt_edad.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel4.setText("AÑOS");

        txt_nombre.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel5.setText("TIPO:");

        cmb_tipo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(SELECCIONE)", "PERRO", "GATO", "TORTUGA", "PATO", "MAPACHE", " " }));

        chk_atenciones.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        chk_atenciones.setText("POSEE ATENCIONES PREVIAS?");
        chk_atenciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_atencionesActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel6.setText("CANTIDAD:");

        txt_cantidad.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_cantidad.setText("0");
        txt_cantidad.setEnabled(false);
        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel7.setText("NOMBRE DUEÑO:");

        txt_dueño.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_dueño.setEnabled(false);
        txt_dueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dueñoActionPerformed(evt);
            }
        });

        chk_dueño.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        chk_dueño.setText("POSEE DUEÑO?");
        chk_dueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_dueñoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel8.setText("DESCRIPCIÓN:");

        btn_almacenar.setText("ALMACENAR");
        btn_almacenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_almacenarActionPerformed(evt);
            }
        });

        btn_limpiar.setText("LIMPIAR");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        jScrollPane1.setToolTipText("");

        txta_descripcion.setColumns(20);
        txta_descripcion.setRows(5);
        jScrollPane1.setViewportView(txta_descripcion);

        jMenu1.setText("Opciones");

        mi_almacenarMascota.setText("Almacenar Macota");
        jMenu1.add(mi_almacenarMascota);

        mi_buscarMascota.setText("Buscar Mascota");
        mi_buscarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_buscarMascotaActionPerformed(evt);
            }
        });
        jMenu1.add(mi_buscarMascota);

        mi_listarMascota.setText("Listar Mascota");
        jMenu1.add(mi_listarMascota);

        mi_eliminarModificar.setText("Eliminar / Modificar");
        jMenu1.add(mi_eliminarModificar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quienes Somos");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(72, 72, 72))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(chk_dueño)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_dueño, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(122, 122, 122)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(chk_atenciones)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_almacenar, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane1))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(0, 22, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chk_atenciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_dueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chk_dueño))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_almacenar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(btn_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void txt_dueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dueñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dueñoActionPerformed

    private void btn_almacenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_almacenarActionPerformed
        ControladorMascota controlM = new ControladorMascota();
        Mascota mascota = new Mascota();
        
        
        
        try{
            
        mascota.setId(mascota.getId());
        if(txt_nombre.getText().length()>50){
        JOptionPane.showMessageDialog(rootPane, "EXCEDE EL LARGO PERMITIDO (50)");
        }else{
        mascota.setNombre(txt_nombre.getText()); 
        }
        
        if(Integer.parseInt(txt_edad.getText())>150||Integer.parseInt(txt_edad.getText())<0){
            JOptionPane.showMessageDialog(rootPane, "EDAD INVALIDA (0 a 150 años");
        }else{
        mascota.setEdad(Integer.parseInt(txt_edad.getText()));
        }
        
        mascota.setTipo(cmb_tipo.getSelectedItem().toString());
        
        
        
        
        mascota.setPosee_atencion(chk_atenciones.isSelected());
        mascota.setCantidad(Integer.parseInt(txt_cantidad.getText()));
        
        
        
        
        mascota.setPosee_dueno(chk_dueño.isSelected());
        mascota.setNombre_dueno(txt_dueño.getText());
        mascota.setDescripcion(txta_descripcion.getText());
        
        controlM.almacenarMascota(mascota);
        JOptionPane.showMessageDialog(rootPane, "MASCOTA ALMACENADA CORRECTAMENTE!!");
        }
        catch(Exception err){
            JOptionPane.showMessageDialog(rootPane, "Error: " + err.getMessage());
        }
        
       
        
        
    }//GEN-LAST:event_btn_almacenarActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void chk_atencionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_atencionesActionPerformed
        if(chk_atenciones.isSelected()==true){
            txt_cantidad.setEnabled(true);
            txt_cantidad.setText("");
        }else{
            txt_cantidad.setEnabled(false);
            txt_cantidad.setText("0");
        }
    }//GEN-LAST:event_chk_atencionesActionPerformed

    private void chk_dueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_dueñoActionPerformed
        if(chk_dueño.isSelected()==true){
            txt_dueño.setEnabled(true);
        }
    }//GEN-LAST:event_chk_dueñoActionPerformed

    private void mi_buscarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_buscarMascotaActionPerformed
        BuscarMascota buscarmascota = new BuscarMascota();
        buscarmascota.setVisible(true);
    }//GEN-LAST:event_mi_buscarMascotaActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        txt_nombre.setText("");
        txt_cantidad.setText("");
        txt_dueño.setText("");
        txt_edad.setText("0");
        chk_atenciones.setSelected(false);
        chk_dueño.setSelected(false);
        txta_descripcion.setText("");
        cmb_tipo.setSelectedItem("(SELECCIONE)");
        
        
    }//GEN-LAST:event_btn_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAlmacenarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAlmacenarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAlmacenarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAlmacenarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAlmacenarMascota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_almacenar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JCheckBox chk_atenciones;
    private javax.swing.JCheckBox chk_dueño;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mi_almacenarMascota;
    private javax.swing.JMenuItem mi_buscarMascota;
    private javax.swing.JMenuItem mi_eliminarModificar;
    private javax.swing.JMenuItem mi_listarMascota;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_dueño;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextArea txta_descripcion;
    // End of variables declaration//GEN-END:variables
}
